### ISSUE TITLE
shinyTree does not seem to be working in shiny 1.5

### ISSUE THREAD

**Issue by earnaud** [shinyTree/shinyTree#99] opened 2020-07-30 15:35 UTC
Hello,

upgrading my application to shiny 1.5 lately, a module of it does not work anymore. I suspect some changes to have happened within shiny. 

My bug is simple: I have created two trees: one with HTML contents in leaves, and one with tree paths in leaves. The aim of the module is to use the second one (`tree`) as a ShinyTree and to fetch content from the first one (`doc`) according to selected path.

The code for my module is the following:
```
documentation <- function(id) {
  moduleServer(id, function(input, output, session) {
    
    # Load data ====
    withProgress(message = "Loading documentation.", {
      doc <- system.file("resources/doc_guideline.json", package = "MetaShARK") %>%
        jsonlite::read_json(simplifyVector = TRUE) %>%
        jsonlite::unserializeJSON()
      incProgress(0.5)
      tree <- system.file("resources/tree_guideline.json", package = "MetaShARK") %>%
        jsonlite::read_json(simplifyVector = TRUE) %>%
        jsonlite::unserializeJSON()
      incProgress(0.5)
    })
    
    # UI render ====
    
    # render tree
    output$tree <- shinyTree::renderTree(tree)
    
    # output selected node
    output$doc <- renderUI({
      browser()
      tree.node <- shinyTree::get_selected(input$tree)
      validate(
        need(unlist(tree.node), "(Select an item first)")
      )
      path <- paste(c(attr(tree.node[[1]], "ancestry"), unlist(tree.node)), collapse = "/")
      doc.node <- followPath(doc, path)
      if ("annotation" %in% names(doc.node)) {
        doc.node$annotation
      } else {
        helpText("No content found at:", path)
      }
    })
  })
}
```

And the files are accessible [there](https://github.com/earnaud/MetaShARK-v2/tree/server-dev/inst/resources) (sorry, json is not supported in GitHub).

This might be a bit raw, tell me if you would like a clearer reprex. Thanks you by advance for any help you could provide !

**Comment by trafficonese** [comment] 2020-07-31 10:11
It's not clear what your bug is and the example is not reproducible. I tried a minified example to just render the tree and get the selections and everything seems to work fine.

I tried it with shiny `1.5.0` and `1.5.0.9001`.

```
library(shiny)
library(shinyTree)
library(jsonlite)

tree <- jsonlite::read_json("https://raw.githubusercontent.com/earnaud/MetaShARK-v2/server-dev/inst/resources/tree_guideline.json", simplifyVector = TRUE) %>% 
  jsonlite::unserializeJSON()

ui <- fluidPage(
  shinyTree("tree"),
  uiOutput("doc")
)

server <- function(input, output, session) {
  output$tree <- shinyTree::renderTree(tree)
  
  output$doc <- renderUI({
    tree.node <- shinyTree::get_selected(input$tree)
    req(length(tree.node) != 0)
    div(paste0(
      paste(attr(tree.node[[1]], "ancestry", exact = T), collapse = " -> "),
      " -> ", tree.node))
  })
}

shinyApp(ui, server)
```

**Comment by earnaud** [comment] 2020-07-31 10:30
Hello,

thanks you a lot for testing this. The exact error message I get is:
```
Warning: Error in <Anonymous>: No handler registered for type documentation-tree:shinyTree
  [No stack trace available]
Error in (function (name, val, shinysession)  : 
  No handler registered for type documentation-tree:shinyTree
```

I got to think Shiny1.5 was the cause of this since some/many things seemed to have changed.

**Comment by trafficonese** [comment] 2020-07-31 10:36
Could you make a Gist or include a minified example that produces this error? It seems the error comes from the other tree (documentation)?

**Comment by earnaud** [comment] 2020-07-31 11:52
I'll have a look at Gist - never used it before.

Also, I am experiencing another thing: I only get an input for `tree-search` but none for `tree`.

**Comment by psychometrician** [comment] 2020-09-01 16:24
I got the same error. one strange thing is that it happens randomly. sometime it works without the error but sometime (just using the same code I ran next day) it doesn't work. 

Warning: Error in <Anonymous>: No handler registered for type rc_k1-tree:shinyTree
  [No stack trace available]
Error in (function (name, val, shinysession)  : 
  No handler registered for type rc_k1-tree:shinyTree

earnaud, are you using golem when creating your shiny app? I was wondering if some other package like golem causes this issue. I replicated my reproducible shinytree module/server without using golem and it worked... 

But the randomly working and not working app is built using golem.

**Comment by earnaud** [comment] 2020-09-02 07:53
I actually use a bunch of packages but got rid of {golem}. The reason is I began to write the app without it and only used a small part of its features. 

Truely, I solved the bug by luck, I do not remember how, badly.

**Comment by JasperSch** [comment] 2020-09-24 09:29
I believe the reason for the error  

Error in : No handler registered for type xxx:shinyTree

is only registering the registerInputHandler() within .onAttach().
E.g. the error occurs when you do not use a library() call first.
I opened a PR #101.

**Comment by ChrKoenig** [comment] 2021-12-20 22:20
Had the same error and got it fixed by removing the inputHandler every time I start the the app. 

```
shinyApp(
      ui = app_ui,
      server = app_server,
      onStart = function(){shiny::removeInputHandler("shinyTree")}
)
```

**Comment by bellma-lilly** [comment] 2022-01-18 20:23
The following should work in golem projects:
suppressMessages(require(shinyTree))

**Comment by nikolasharing** [comment] 2022-04-12 10:45
@bellma-lilly Your solution worked in my {golem} app. What is the reason behind this? Why can't I just use the NAMESPACE file to import the libraries?

**Comment by bellma-lilly** [comment] 2022-04-13 13:25
@nikolasharing shinyTree registers an input handler when the library is loaded, but golem does not actually load the library, it just makes the functions available. I'm sure there is a good reason for this, but I'm not a golem user, so I'm not sure what it is.

**Closed by bellma-lilly** 2022-04-13 13:25 UTC
